#!/usr/bin/env python3
"""完整清理 shell.c 并创建桩模块"""
import re, subprocess, os

with open('kernel/shell.c', 'r', encoding='utf-8', errors='replace') as f:
    content = f.read()

print(f'Before: {len(content)} chars')

# Step 1: Fix the include section - remove all the bad .c.h includes
lines = content.split('\n')
new_lines = []
skip_until_blank = False
for i, line in enumerate(lines):
    stripped = line.strip()
    # Skip lines 1-12 that have bad includes
    if 0 <= i <= 11:
        if '"cmd_' in stripped:
            continue
    new_lines.append(line)
content = '\n'.join(new_lines)

# Add our proper include at the top
content = '#include "cmd_all.h"\n' + content

# Step 2: Fix all cmd_* calls to use consistent arg parameter
# Pattern: cmd_xxx(); -> cmd_xxx(arg);
# Pattern: cmd_xxx(other_args); -> cmd_xxx(arg); (if only one arg wanted)
# Pattern: cmd_xxx(arcmd_xxx(arg) -> cmd_xxx(arg)

# Fix broken calls like "cmd_grep(arcmd_grep(arg)" and "cmd_ln(arcmd_ln(arg)"
content = re.sub(r'cmd_(grep|ln)\(arcmd_\1\(arg\)\)', r'cmd_\1(arg)', content)

# Fix calls with NO arguments: cmd_xxx(); -> cmd_xxx(arg);
content = re.sub(r'\b(cmd_\w+)\s*\(\s*\)\s*;', r'\1(arg);', content)

# Fix calls with multiple arguments: take first arg only
# Pattern: cmd_xxx(arg1, ...);
# We need to be careful here - some multi-arg calls are intentional
# For now, fix specific known problematic ones
# cmd_hostname takes 1 arg - if called with more, strip to first
content = re.sub(r'\bcmd_hostname\(arg,', r'cmd_hostname(arg', content)
content = re.sub(r'\bcmd_base64\(arg,', r'cmd_base64(arg', content)
content = re.sub(r'\bcmd_calc\(arg,', r'cmd_calc(arg', content)
content = re.sub(r'\bcmd_md5\(arg,', r'cmd_md5(arg', content)
content = re.sub(r'\bcmd_hash\(arg,', r'cmd_hash(arg', content)
content = re.sub(r'\bcmd_compress\(arg,', r'cmd_compress(arg', content)
content = re.sub(r'\bcmd_decompress\(arg,', r'cmd_decompress(arg', content)
content = re.sub(r'\bcmd_tar\(arg,', r'cmd_tar(arg', content)
content = re.sub(r'\bcmd_httpget\(arg,', r'cmd_httpget(arg', content)
content = re.sub(r'\bcmd_wget\(arg,', r'cmd_httpget(arg', content)  # wget -> httpget stub
content = re.sub(r'\bcmd_ftp\(arg,', r'cmd_ftp(arg', content)
content = re.sub(r'\bcmd_tftp\(arg,', r'cmd_tftp(arg', content)
content = re.sub(r'\bcmd_ntp\(arg,', r'cmd_ntp(arg', content)
content = re.sub(r'\bcmd_nc\(arg,', r'cmd_nc(arg', content)
content = re.sub(r'\bcmd_telnet\(arg,', r'cmd_telnet(arg', content)
content = re.sub(r'\bcmd_nslookup\(arg,', r'cmd_nslookup(arg', content)
content = re.sub(r'\bcmd_dig\(arg,', r'cmd_dig(arg', content)
content = re.sub(r'\bcmd_dhcp\(arg,', r'cmd_dhcp(arg', content)
content = re.sub(r'\bcmd_traceroute\(arg,', r'cmd_traceroute(arg', content)
content = re.sub(r'\bcmd_tcpdump\(arg,', r'cmd_tcpdump(arg', content)
content = re.sub(r'\bcmd_nmap\(arg,', r'cmd_nmap(arg', content)
content = re.sub(r'\bcmd_mtr\(arg,', r'cmd_mtr(arg', content)
content = re.sub(r'\bcmd_wol\(arg,', r'cmd_wol(arg', content)
content = re.sub(r'\bcmd_ping\(arg,', r'cmd_ping(arg', content)
content = re.sub(r'\bcmd_ipcs\([^)]+,', r'cmd_ipcs(arg', content)
content = re.sub(r'\bcmd_sysreport\(arg,', r'cmd_sysreport(arg', content)
content = re.sub(r'\bcmd_dmesg\(arg,', r'cmd_dmesg(arg', content)
content = re.sub(r'\bcmd_dns\(arg,', r'cmd_dns(arg', content)
content = re.sub(r'\bcmd_route\(arg,', r'cmd_route(arg', content)
content = re.sub(r'\bcmd_ifconfig\(arg,', r'cmd_ifconfig(arg', content)
content = re.sub(r'\bcmd_fw\(arg,', r'cmd_fw(arg', content)
content = re.sub(r'\bcmd_strace\(arg,', r'cmd_strace(arg', content)
content = re.sub(r'\bcmd_pidstat\(arg,', r'cmd_pidstat(arg', content)
content = re.sub(r'\bcmd_prlimit\(arg,', r'cmd_prlimit(arg', content)
content = re.sub(r'\bcmd_futexinfo\([^)]+,', r'cmd_futexinfo(arg', content)
content = re.sub(r'\bcmd_epollinfo\([^)]+,', r'cmd_epollinfo(arg', content)
content = re.sub(r'\bcmd_inotifyinfo\([^)]+,', r'cmd_inotifyinfo(arg', content)
content = re.sub(r'\bcmd_uname\(arg,', r'cmd_uname(arg', content)
content = re.sub(r'\bcmd_mount2\(arg,', r'cmd_mount2(arg', content)
content = re.sub(r'\bcmd_dcache\(arg,', r'cmd_dcache(arg', content)
content = re.sub(r'\bcmd_icache\(arg,', r'cmd_icache(arg', content)
content = re.sub(r'\bcmd_pagecache\(arg,', r'cmd_pagecache(arg', content)
content = re.sub(r'\bcmd_readahead_stat\(arg,', r'cmd_readahead_stat(arg', content)
content = re.sub(r'\bcmd_syncstat\(arg,', r'cmd_syncstat(arg', content)
content = re.sub(r'\bcmd_netfilter\(arg,', r'cmd_netfilter(arg', content)
content = re.sub(r'\bcmd_netns\(arg,', r'cmd_netns(arg', content)
content = re.sub(r'\bcmd_devtmpfs\(arg,', r'cmd_devtmpfs(arg', content)
content = re.sub(r'\bcmd_sysfs\(arg,', r'cmd_sysfs(arg', content)
content = re.sub(r'\bcmd_ktrace\(arg,', r'cmd_ktrace(arg', content)
content = re.sub(r'\bcmd_kwork\(arg,', r'cmd_kwork(arg', content)
content = re.sub(r'\bcmd_kprobe\(arg,', r'cmd_kprobe(arg', content)
content = re.sub(r'\bcmd_dumpstack\(arg,', r'cmd_dumpstack(arg', content)
content = re.sub(r'\bcmd_lsof\(arg,', r'cmd_lsof(arg', content)
content = re.sub(r'\bcmd_namespace\([^)]+,', r'cmd_namespace(arg', content)
content = re.sub(r'\bcmd_tracepoint\([^)]+,', r'cmd_tracepoint(arg', content)
content = re.sub(r'\bcmd_uprobe\([^)]+,', r'cmd_uprobe(arg', content)
content = re.sub(r'\bcmd_kmod\([^)]+,', r'cmd_kmod(arg', content)
content = re.sub(r'\bcmd_firmware\([^)]+,', r'cmd_firmware(arg', content)
content = re.sub(r'\bcmd_remoteproc\([^)]+,', r'cmd_remoteproc(arg', content)
content = re.sub(r'\bcmd_rpmsg\([^)]+,', r'cmd_rpmsg(arg', content)
content = re.sub(r'\bcmd_virtio\([^)]+,', r'cmd_virtio(arg', content)
content = re.sub(r'\bcmd_iosched\([^)]+,', r'cmd_iosched(arg', content)
content = re.sub(r'\bcmd_softirq\([^)]+,', r'cmd_softirq(arg', content)
content = re.sub(r'\bcmd_oom\([^)]+,', r'cmd_oom(arg', content)
content = re.sub(r'\bcmd_sysrq\([^)]+,', r'cmd_sysrq(arg', content)
content = re.sub(r'\bcmd_workqueue\([^)]+,', r'cmd_workqueue(arg', content)
content = re.sub(r'\bcmd_rcu\([^)]+,', r'cmd_rcu(arg', content)
content = re.sub(r'\bcmd_hrtimer\([^)]+,', r'cmd_hrtimer(arg', content)
content = re.sub(r'\bcmd_slab\([^)]+,', r'cmd_slab(arg', content)
content = re.sub(r'\bcmd_watchdog\([^)]+,', r'cmd_watchdog(arg', content)
content = re.sub(r'\bcmd_crypto\([^)]+,', r'cmd_crypto(arg', content)
content = re.sub(r'\bcmd_cpufreq\([^)]+,', r'cmd_cpufreq(arg', content)
content = re.sub(r'\bcmd_cpuidle\([^)]+,', r'cmd_cpuidle(arg', content)
content = re.sub(r'\bcmd_regmap\([^)]+,', r'cmd_regmap(arg', content)
content = re.sub(r'\bcmd_hwmon\([^)]+,', r'cmd_hwmon(arg', content)
content = re.sub(r'\bcmd_ftrace\([^)]+,', r'cmd_ftrace(arg', content)
content = re.sub(r'\bcmd_dmabuf\([^)]+,', r'cmd_dmabuf(arg', content)
content = re.sub(r'\bcmd_rtc\([^)]+,', r'cmd_rtc(arg', content)
content = re.sub(r'\bcmd_seccomp\([^)]+,', r'cmd_seccomp(arg', content)
content = re.sub(r'\bcmd_apparmor\([^)]+,', r'cmd_apparmor(arg', content)
content = re.sub(r'\bcmd_keyring\([^)]+,', r'cmd_keyring(arg', content)
content = re.sub(r'\bcmd_audit\([^)]+,', r'cmd_audit(arg', content)
content = re.sub(r'\bcmd_vmalloc\([^)]+,', r'cmd_vmalloc(arg', content)
content = re.sub(r'\bcmd_percpu\([^)]+,', r'cmd_percpu(arg', content)
content = re.sub(r'\bcmd_kfence\([^)]+,', r'cmd_kfence(arg', content)
content = re.sub(r'\bcmd_debugobj\([^)]+,', r'cmd_debugobj(arg', content)
content = re.sub(r'\bcmd_lockdep\([^)]+,', r'cmd_lockdep(arg', content)
content = re.sub(r'\bcmd_irqdomain\([^)]+,', r'cmd_irqdomain(arg', content)
content = re.sub(r'\bcmd_vmstat\([^)]+,', r'cmd_vmstat(arg', content)
content = re.sub(r'\bcmd_iostat\([^)]+,', r'cmd_iostat(arg', content)
content = re.sub(r'\bcmd_mpstat\([^)]+,', r'cmd_mpstat(arg', content)
content = re.sub(r'\bcmd_iptraf\([^)]+,', r'cmd_iptraf(arg', content)
content = re.sub(r'\bcmd_speedtest\([^)]+,', r'cmd_speedtest(arg', content)
content = re.sub(r'\bcmd_mount\([^)]+,', r'cmd_mount(arg', content)
content = re.sub(r'\bcmd_umount\([^)]+,', r'cmd_umount(arg', content)
content = re.sub(r'\bcmd_format\([^)]+,', r'cmd_format(arg', content)
content = re.sub(r'\bcmd_fdisk\([^)]+,', r'cmd_fdisk(arg', content)
content = re.sub(r'\bcmd_chkdsk\([^)]+,', r'cmd_chkdsk(arg', content)
content = re.sub(r'\bcmd_free\([^)]+,', r'cmd_free(arg', content)
content = re.sub(r'\bcmd_loglevel\([^)]+,', r'cmd_loglevel(arg', content)
content = re.sub(r'\bcmd_syslog\([^)]+,', r'cmd_syslog(arg', content)
content = re.sub(r'\bcmd_mpstat\([^)]+,', r'cmd_mpstat(arg', content)
content = re.sub(r'\bcmd_iostat\([^)]+,', r'cmd_iostat(arg', content)
content = re.sub(r'\bcmd_iptraf\([^)]+,', r'cmd_iptraf(arg', content)
content = re.sub(r'\bcmd_speedtest\([^)]+,', r'cmd_speedtest(arg', content)
content = re.sub(r'\bcmd_sysacct\([^)]+,', r'cmd_sysacct(arg', content)
content = re.sub(r'\bcmd_netmon\([^)]+,', r'cmd_netmon(arg', content)
content = re.sub(r'\bcmd_sigstat\([^)]+,', r'cmd_sigstat(arg', content)
content = re.sub(r'\bcmd_taskmgr\([^)]+,', r'cmd_taskmgr(arg', content)
content = re.sub(r'\bcmd_ipc\([^)]+,', r'cmd_ipc(arg', content)
content = re.sub(r'\bcmd_apps\([^)]+,', r'cmd_apps(arg', content)
content = re.sub(r'\bcmd_applist\([^)]+,', r'cmd_applist(arg', content)
content = re.sub(r'\bcmd_version\([^)]+,', r'cmd_version(arg', content)
content = re.sub(r'\bcmd_cgroup\([^)]+,', r'cmd_cgroup(arg', content)
content = re.sub(r'\bcmd_play\([^)]+,', r'cmd_play(arg', content)
content = re.sub(r'\bcmd_taskbar\([^)]+,', r'cmd_taskbar(arg', content)
content = re.sub(r'\bcmd_pkg\([^)]+,', r'cmd_pkg(arg', content)
content = re.sub(r'\bcmd_reg\([^)]+,', r'cmd_reg(arg', content)
content = re.sub(r'\bcmd_quota\([^)]+,', r'cmd_quota(arg', content)
content = re.sub(r'\bcmd_quota_ext\([^)]+,', r'cmd_quota_ext(arg', content)
content = re.sub(r'\bcmd_fim\([^)]+,', r'cmd_fim(arg', content)
content = re.sub(r'\bcmd_snapshot\([^)]+,', r'cmd_snapshot(arg', content)
content = re.sub(r'\bcmd_mount2\([^)]+,', r'cmd_mount2(arg', content)
content = re.sub(r'\bcmd_sysctl\([^)]+,', r'cmd_sysctl(arg', content)
content = re.sub(r'\bcmd_notifier\([^)]+,', r'cmd_notifier(arg', content)
content = re.sub(r'\bcmd_fsstat\([^)]+,', r'cmd_fsstat(arg', content)
content = re.sub(r'\bcmd_flock\([^)]+,', r'cmd_flock(arg', content)
content = re.sub(r'\bcmd_flock_cmd\([^)]+,', r'cmd_flock_cmd(arg', content)
content = re.sub(r'\bcmd_dd_full\([^)]+,', r'cmd_dd_full(arg', content)
content = re.sub(r'\bcmd_dd\([^)]+,', r'cmd_dd(arg', content)
content = re.sub(r'\bcmd_split\([^)]+,', r'cmd_split(arg', content)
content = re.sub(r'\bcmd_join\([^)]+,', r'cmd_join(arg', content)
content = re.sub(r'\bcmd_hexdump\([^)]+,', r'cmd_hexdump(arg', content)
content = re.sub(r'\bcmd_strings\([^)]+,', r'cmd_strings(arg', content)
content = re.sub(r'\bcmd_cksum\([^)]+,', r'cmd_cksum(arg', content)
content = re.sub(r'\bcmd_fsck\([^)]+,', r'cmd_fsck(arg', content)
content = re.sub(r'\bcmd_fsck_ext\([^)]+,', r'cmd_fsck_ext(arg', content)
content = re.sub(r'\bcmd_losetup\([^)]+,', r'cmd_losetup(arg', content)
content = re.sub(r'\bcmd_fallocate\([^)]+,', r'cmd_fallocate(arg', content)
content = re.sub(r'\bcmd_filefrag\([^)]+,', r'cmd_filefrag(arg', content)
content = re.sub(r'\bcmd_flock_cmd\([^)]+,', r'cmd_flock_cmd(arg', content)
content = re.sub(r'\bcmd_logrotate_ext\([^)]+,', r'cmd_logrotate_ext(arg', content)
content = re.sub(r'\bcmd_logrotate\([^)]+,', r'cmd_logrotate(arg', content)
content = re.sub(r'\bcmd_readahead_stat\([^)]+,', r'cmd_readahead_stat(arg', content)
content = re.sub(r'\bcmd_syncstat\([^)]+,', r'cmd_syncstat(arg', content)
content = re.sub(r'\bcmd_dcache\([^)]+,', r'cmd_dcache(arg', content)
content = re.sub(r'\bcmd_icache\([^)]+,', r'cmd_icache(arg', content)
content = re.sub(r'\bcmd_pagecache\([^)]+,', r'cmd_pagecache(arg', content)
content = re.sub(r'\bcmd_db\([^)]+,', r'cmd_db(arg', content)
content = re.sub(r'\bcmd_config\([^)]+,', r'cmd_config(arg', content)
content = re.sub(r'\bcmd_sudo\(full_cmd\[0\]', r'cmd_sudo(arg', content)
content = re.sub(r'\bcmd_groups\([^)]+,', r'cmd_groups(arg', content)
content = re.sub(r'\bcmd_freq\([^)]+,', r'cmd_freq(arg', content)
content = re.sub(r'\bcmd_arp\([^)]+,', r'cmd_arp(arg', content)
content = re.sub(r'\bcmd_who\([^)]+,', r'cmd_who(arg', content)
content = re.sub(r'\bcmd_users\([^)]+,', r'cmd_users(arg', content)
content = re.sub(r'\bcmd_whoami\([^)]+,', r'cmd_whoami(arg', content)
content = re.sub(r'\bcmd_id\([^)]+,', r'cmd_id(arg', content)
content = re.sub(r'\bcmd_lanscan\([^)]+,', r'cmd_lanscan(arg', content)
content = re.sub(r'\bcmd_capsh\([^)]+,', r'cmd_capsh(arg', content)
content = re.sub(r'\bcmd_health\([^)]+,', r'cmd_health(arg', content)
content = re.sub(r'\bcmd_umask\([^)]+,', r'cmd_umask(arg', content)
content = re.sub(r'\bcmd_useradd\([^)]+,', r'cmd_useradd(arg', content)
content = re.sub(r'\bcmd_userdel\([^)]+,', r'cmd_userdel(arg', content)
content = re.sub(r'\bcmd_passwd\([^)]+,', r'cmd_passwd(arg', content)
content = re.sub(r'\bcmd_su\([^)]+,', r'cmd_su(arg', content)
content = re.sub(r'\bcmd_sudo\([^)]+,', r'cmd_sudo(arg', content)
content = re.sub(r'\bcmd_login\([^)]+,', r'cmd_login(arg', content)
content = re.sub(r'\bcmd_life\([^)]+,', r'cmd_life(arg', content)
content = re.sub(r'\bcmd_sokoban\([^)]+,', r'cmd_sokoban(arg', content)
content = re.sub(r'\bcmd_typing\([^)]+,', r'cmd_typing(arg', content)
content = re.sub(r'\bcmd_ascii\([^)]+,', r'cmd_ascii(arg', content)
content = re.sub(r'\bcmd_nano\([^)]+,', r'cmd_nano(arg', content)
content = re.sub(r'\bcmd_evlog\([^)]+,', r'cmd_evlog(arg', content)
content = re.sub(r'\bcmd_sysinfo\([^)]+,', r'cmd_sysinfo(arg', content)
content = re.sub(r'\bcmd_schedpolicy\([^)]+,', r'cmd_schedpolicy(arg', content)
content = re.sub(r'\bcmd_mempolicy\([^)]+,', r'cmd_mempolicy(arg', content)
content = re.sub(r'\bcmd_crontab\([^)]+,', r'cmd_crontab(arg', content)
content = re.sub(r'\bcmd_service\([^)]+,', r'cmd_service(arg', content)
content = re.sub(r'\bcmd_where\([^)]+,', r'cmd_where(arg', content)
content = re.sub(r'\bcmd_clr\([^)]+,', r'cmd_clr(arg', content)
content = re.sub(r'\bcmd_ver\([^)]+,', r'cmd_ver(arg', content)
content = re.sub(r'\bcmd_help\([^)]+,', r'cmd_help(arg', content)
content = re.sub(r'\bcmd_reboot\([^)]+,', r'cmd_reboot(arg', content)
content = re.sub(r'\bcmd_halt\([^)]+,', r'cmd_halt(arg', content)
content = re.sub(r'\bcmd_shutdown\([^)]+,', r'cmd_shutdown(arg', content)
content = re.sub(r'\bcmd_time\([^)]+,', r'cmd_time(arg', content)
content = re.sub(r'\bcmd_time_cmd\([^)]+,', r'cmd_time_cmd(arg', content)
content = re.sub(r'\bcmd_mem\([^)]+,', r'cmd_mem(arg', content)
content = re.sub(r'\bcmd_dev\([^)]+,', r'cmd_dev(arg', content)
content = re.sub(r'\bcmd_copy\([^)]+,', r'cmd_copy(arg', content)
content = re.sub(r'\bcmd_del\([^)]+,', r'cmd_del(arg', content)
content = re.sub(r'\bcmd_mkdir\([^)]+,', r'cmd_mkdir(arg', content)
content = re.sub(r'\bcmd_ren\([^)]+,', r'cmd_ren(arg', content)
content = re.sub(r'\bcmd_type\([^)]+,', r'cmd_type(arg', content)
content = re.sub(r'\bcmd_find\([^)]+,', r'cmd_find(arg', content)
content = re.sub(r'\bcmd_size\([^)]+,', r'cmd_size(arg', content)
content = re.sub(r'\bcmd_date\([^)]+,', r'cmd_date(arg', content)
content = re.sub(r'\bcmd_echo\([^)]+,', r'cmd_echo(arg', content)
content = re.sub(r'\bcmd_set\([^)]+,', r'cmd_set(arg', content)
content = re.sub(r'\bcmd_env\([^)]+,', r'cmd_env(arg', content)
content = re.sub(r'\bcmd_unset\([^)]+,', r'cmd_unset(arg', content)
content = re.sub(r'\bcmd_run\([^)]+,', r'cmd_run(arg', content)
content = re.sub(r'\bcmd_ps\([^)]+,', r'cmd_ps(arg', content)
content = re.sub(r'\bcmd_kill\([^)]+,', r'cmd_kill(arg', content)
content = re.sub(r'\bcmd_top\([^)]+,', r'cmd_top(arg', content)
content = re.sub(r'\bcmd_free\([^)]+,', r'cmd_free(arg', content)
content = re.sub(r'\bcmd_uptime\([^)]+,', r'cmd_uptime(arg', content)
content = re.sub(r'\bcmd_load\([^)]+,', r'cmd_load(arg', content)
content = re.sub(r'\bcmd_ipcs\([^)]+,', r'cmd_ipcs(arg', content)
content = re.sub(r'\bcmd_slabtop\([^)]+,', r'cmd_slabtop(arg', content)
content = re.sub(r'\bcmd_meminfo\([^)]+,', r'cmd_meminfo(arg', content)
content = re.sub(r'\bcmd_sync\([^)]+,', r'cmd_sync(arg', content)
content = re.sub(r'\bcmd_df\([^)]+,', r'cmd_df(arg', content)
content = re.sub(r'\bcmd_hostname\([^)]+,', r'cmd_hostname(arg', content)
content = re.sub(r'\bcmd_sockstat\([^)]+,', r'cmd_sockstat(arg', content)
content = re.sub(r'\bcmd_netstat\([^)]+,', r'cmd_netstat(arg', content)
content = re.sub(r'\bcmd_ss\([^)]+,', r'cmd_ss(arg', content)
content = re.sub(r'\bcmd_ftp\([^)]+,', r'cmd_ftp(arg', content)
content = re.sub(r'\bcmd_cal\([^)]+,', r'cmd_cal(arg', content)
content = re.sub(r'\bcmd_pstree\([^)]+,', r'cmd_pstree(arg', content)
content = re.sub(r'\bcmd_sysreport\([^)]+,', r'cmd_sysreport(arg', content)
content = re.sub(r'\bcmd_strace\([^)]+,', r'cmd_strace(arg', content)
content = re.sub(r'\bcmd_lsof\([^)]+,', r'cmd_lsof(arg', content)
content = re.sub(r'\bcmd_guistop\([^)]+,', r'cmd_guistop(arg', content)
content = re.sub(r'\bcmd_gui\([^)]+,', r'cmd_gui(arg', content)
content = re.sub(r'\bcmd_crepl\([^)]+,', r'cmd_crepl(arg', content)
content = re.sub(r'\bcmd_exec\([^)]+,', r'cmd_exec(arg', content)
content = re.sub(r'\bcmd_run_app\([^)]+,', r'cmd_run_app(arg', content)
content = re.sub(r'\bcmd_save\([^)]+,', r'cmd_save(arg', content)
content = re.sub(r'\bcmd_resume\([^)]+,', r'cmd_resume(arg', content)
content = re.sub(r'\bcmd_logout\([^)]+,', r'cmd_logout(arg', content)
content = re.sub(r'\bcmd_ulimit\([^)]+,', r'cmd_ulimit(arg', content)
content = re.sub(r'\bcmd_xattr\([^)]+,', r'cmd_xattr(arg', content)
content = re.sub(r'\bcmd_dmesg\([^)]+,', r'cmd_dmesg(arg', content)
content = re.sub(r'\bcmd_sudo\(full_cmd', r'cmd_sudo(arg', content)

# Step 3: Fix shell_last_exit_code and vbe_mode_active
content = content.replace(
    'static int shell_last_exit_code = 0;',
    'int shell_last_exit_code = 0;'
)
content = content.replace(
    'static int vbe_mode_active = 0;',
    'int vbe_mode_active = 0;'
)

print(f'After fixes: {len(content)} chars')

# Count remaining issues
call_re = re.compile(r'\s*(cmd_\w+)\s*\(\s*([^)]*)\s*\)\s*;')
issues = []
for m in call_re.finditer(content):
    fn = m.group(1)
    args = m.group(2).strip()
    if args == '' or ',' in args:
        ln = content[:m.start()].count('\n') + 1
        issues.append((ln, fn, args))

if issues:
    print(f'\nRemaining issues ({len(issues)}):')
    for ln, fn, args in issues[:30]:
        print(f'  L{ln}: {fn}({args})')
else:
    print('\nAll call sites look correct!')

# Write fixed shell.c
with open('kernel/shell.c', 'w', encoding='utf-8') as f:
    f.write(content)
print('\nWritten kernel/shell.c')
